---
# tasks file for roles/prueba
- name: Instalación de firewalld
  yum:
   name: firewalld
   state: latest

- name: Instalación de httpd
  yum:
   name: "{{ item }}"
   state: latest
  with_items:
   - "{{ httpd_pkg }}"

- name: Iniciación del servicio httpd
  service:
   name: "{{ httpd_srv }}"
   enabled: true
   state: started

- name: Configuración de puerto "{{ port }}"
  lineinfile:
   path: /etc/httpd/conf/httpd.conf
   regexp: '^(.*)Listen (.*)$'
   line: 'Listen {{ port }}'
  notify:
  - restart_httpd

- name: Creación de index.html
  copy:
    content: "HOLA"
    dest: /var/www/html/index.html
