---
#- name: Obtención de las credenciales
#  include_vars: pass.yml
- name: Solo si esta en la BBDD
  block:
    - name: Add the user {{name}}
      user:
        name: "{{name}}"
        password: "{{usr[name].password}}"
        comment: "{{usr[name].fullname}}"
        non_unique: yes
      when: action == 'create'

    - name: Delete the user {{name}}
      user:
        name: "{{name}}"
        state: absent
        remove: yes
      when: action == 'delete'

    - name: Copiado de archivo README.md
      copy: 
        src: README.md
        dest: /home/{{name}}
        force: yes
      when: action == 'create'
    
    - name: Copiado de archivo personalizado
      template:
        src: personalizado.j2
        dest: /home/{{name}}/content.md
      when: action == 'create'

    # - name: Copiado de archivo personalizado
    #   copy:
    #     content: "Home del usuario {{name}}, created by Ansible on {{ '%Y-%m-%d' | strftime }}"
    #     dest: /home/{{name}}/content.md
    #   when: action == 'create'
  when: name is defined and name != '' and name in usr

- name: Instalación de todos los usuarios a la vez
  user:
    name: "{{item.value.name}}"
    password: "{{item.value.password}}"
    comment: "{{item.value.fullname}}"
    non_unique: yes
  loop: "{{ usr | dict2items }}"
  loop_control:
    label: "{{item.value.name}}"
  when: action == 'create' and name == 'all'

- debug:
    msg: "No ha introducido la acción create o delete"
  when: action != 'create' and action != 'delete'

- debug:
    msg: "El nombre que ha introducido no existe en la BBDD"
  when: name not in usr and name != 'all'

- debug:
    msg: "No existe el borrado masivo de usuarios"
  when: name == 'all' and action == 'delete'

